export * from './dashboard-processes.component';
export * from './processes-detail/processes-detail.component';
export * from './processes-detail/processes-detail-header/processes-detail-header.component';
export * from './processes-detail/processes-detail-information/processes-detail-information.component';
export * from './processes-detail/processes-detail-first-step/processes-detail-first-step.component';
export * from './processes-detail/processes-detail-second-step/processes-detail-second-step.component';
export * from './processes-detail/processes-detail-third-step/processes-detail-third-step.component';
export * from './processes-detail/processes-detail-fourth-step/processes-detail-fourth-step.component';
export * from './processes-detail/processes-detail-fifth-step/processes-detail-fifth-step.component';