export * from './chat.service';
import { ChatService } from './chat.service';
export * from './comment.service';
import { CommentService } from './comment.service';
export * from './compensations.service';
import { CompensationsService } from './compensations.service';
export * from './contacts.service';
import { ContactsService } from './contacts.service';
export * from './feedBack.service';
import { FeedBackService } from './feedBack.service';
export * from './files.service';
import { FilesService } from './files.service';
export * from './filesMyHr.service';
import { FilesMyHrService } from './filesMyHr.service';
export * from './groupThing.service';
import { GroupThingService } from './groupThing.service';
export * from './home.service';
import { HomeService } from './home.service';
export * from './inquiries.service';
import { InquiriesService } from './inquiries.service';
export * from './lead.service';
import { LeadService } from './lead.service';
export * from './leadingCompanies.service';
import { LeadingCompaniesService } from './leadingCompanies.service';
export * from './monthlyTransferBlock.service';
import { MonthlyTransferBlockService } from './monthlyTransferBlock.service';
export * from './processes.service';
import { ProcessesService } from './processes.service';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './register.service';
import { RegisterService } from './register.service';
export * from './signIn.service';
import { SignInService } from './signIn.service';
export * from './uploadFile.service';
import { UploadFileService } from './uploadFile.service';
export const APIS = [ChatService, CommentService, CompensationsService, ContactsService, FeedBackService, FilesService, FilesMyHrService, GroupThingService, HomeService, InquiriesService, LeadService, LeadingCompaniesService, MonthlyTransferBlockService, ProcessesService, ProductsService, RegisterService, SignInService, UploadFileService];
