export * from './bank.service';
import { BankService } from './bank.service';
import { ChatService } from './chat.service';
import { CommentService } from './comment.service';
import { CompensationsService } from './compensations.service';
import { ContactsService } from './contacts.service';
import { EmployeesService } from './employees.service';
import { ExceptionsService } from './exceptions.service';
import { FeedBackService } from './feedBack.service';
import { FilesService } from './files.service';
import { FilesMyHrService } from './filesMyHr.service';
import { GroupThingService } from './groupThing.service';
import { HomeService } from './home.service';
import { InquiriesService } from './inquiries.service';
import { LeadService } from './lead.service';
import { LeadingCompaniesService } from './leadingCompanies.service';
import { MenoraService } from './menora.service';
import { MonthlyTransferBlockService } from './monthlyTransferBlock.service';
import { OrganizationsService } from './organizations.service';
import { ProcessesService } from './processes.service';
import { ProductsService } from './products.service';
import { RegisterService } from './register.service';
import { SignInService } from './signIn.service';
import { UploadFileService } from './uploadFile.service';
import { UserService } from './user.service';

export * from './chat.service';
export * from './comment.service';
export * from './compensations.service';
export * from './contacts.service';
export * from './employees.service';
export * from './exceptions.service';
export * from './feedBack.service';
export * from './files.service';
export * from './filesMyHr.service';
export * from './groupThing.service';
export * from './home.service';
export * from './inquiries.service';
export * from './lead.service';
export * from './leadingCompanies.service';
export * from './menora.service';
export * from './monthlyTransferBlock.service';
export * from './organizations.service';
export * from './processes.service';
export * from './products.service';
export * from './register.service';
export * from './signIn.service';
export * from './uploadFile.service';
export * from './user.service';
export const APIS = [BankService, ChatService, CommentService, CompensationsService, ContactsService, EmployeesService, ExceptionsService, FeedBackService, FilesService, FilesMyHrService, GroupThingService, HomeService, InquiriesService, LeadService, LeadingCompaniesService, MenoraService, MonthlyTransferBlockService, OrganizationsService, ProcessesService, ProductsService, RegisterService, SignInService, UploadFileService, UserService];
