/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AccountType = 'max' | 'company' | 'we';

export const AccountType = {
    Max: 'max' as AccountType,
    Company: 'company' as AccountType,
    We: 'we' as AccountType
};

