/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentTypes } from './documentTypes';


export interface ApiDocumentsBody { 
    opswatIds?: string;
    description?: string;
    date?: string;
    employer_id?: number;
    documentType?: DocumentTypes;
}
export namespace ApiDocumentsBody {
}


