/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApigeneralscommentCriteria { 
    organization_id?: string;
    employer_id?: number;
    department_id?: string;
    event_code?: string;
    page?: number;
    limit?: number;
}

