/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Apigenerals1newInquiryInquiry { 
    contact_list?: Array<number>;
    emails_list?: Array<string>;
    isReference?: boolean;
    isAttachFile?: boolean;
    isIncorrectEmployees?: boolean;
    employer_id?: number;
    objectID?: number;
    contentType?: string;
    company_id?: number;
    product_name?: string;
    activeContentType?: string;
    content_type?: string;
}

