/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiproductsfullCompanyBankAccount } from './apiproductsfullCompanyBankAccount';
import { ProductType } from './productType';


export interface ApiproductsfullCompanyProduct { 
    id?: number;
    name?: string;
    code?: string;
    number_a_max?: number;
    is_active?: boolean;
    company_id?: string;
    company_name?: string;
    company_code?: string;
    type?: ProductType;
    full_name?: string;
    bank_account?: Array<ApiproductsfullCompanyBankAccount>;
}
export namespace ApiproductsfullCompanyProduct {
}


