/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiproductsfullCompanyBankAccount { 
    id?: number;
    account_number?: string;
    bank_id?: string;
    branch_id?: string;
    branch_number?: string;
    bank_number?: string;
    is_primary?: boolean;
    is_active?: boolean;
    branch_name?: string;
    bank_name?: string;
    name?: string;
}

