/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ClauseType = 'compensation' | 'employee_benefits' | 'employer_benefits' | 'self_employeed_benefits' | 'ipi_employee' | 'ipi_employer' | 'other_employee' | 'other_employer';

export const ClauseType = {
    Compensation: 'compensation' as ClauseType,
    EmployeeBenefits: 'employee_benefits' as ClauseType,
    EmployerBenefits: 'employer_benefits' as ClauseType,
    SelfEmployeedBenefits: 'self_employeed_benefits' as ClauseType,
    IpiEmployee: 'ipi_employee' as ClauseType,
    IpiEmployer: 'ipi_employer' as ClauseType,
    OtherEmployee: 'other_employee' as ClauseType,
    OtherEmployer: 'other_employer' as ClauseType
};

