/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type CodeErrorFile = 'invalid_file_name' | 'file_unreadable' | 'invalid_xml_structure' | 'primary_hierarchy_invalid_file' | 'ok_receive_file_level_error_message' | 'amount_records_not_appropriate_review_entry' | 'total_provision_not_appropriate_closing_record' | 'monthly_amount_files_greater_senders' | 'file_date_early' | 'file_date_too_early' | 'future_file_date' | 'totals_not_match_the_report' | 'empty' | 'accepting_valid_file' | 'amount_feedback_records_not_appropriate_file_answered' | 'zip_file_not_opened/unreadable';

export const CodeErrorFile = {
    InvalidFileName: 'invalid_file_name' as CodeErrorFile,
    FileUnreadable: 'file_unreadable' as CodeErrorFile,
    InvalidXmlStructure: 'invalid_xml_structure' as CodeErrorFile,
    PrimaryHierarchyInvalidFile: 'primary_hierarchy_invalid_file' as CodeErrorFile,
    OkReceiveFileLevelErrorMessage: 'ok_receive_file_level_error_message' as CodeErrorFile,
    AmountRecordsNotAppropriateReviewEntry: 'amount_records_not_appropriate_review_entry' as CodeErrorFile,
    TotalProvisionNotAppropriateClosingRecord: 'total_provision_not_appropriate_closing_record' as CodeErrorFile,
    MonthlyAmountFilesGreaterSenders: 'monthly_amount_files_greater_senders' as CodeErrorFile,
    FileDateEarly: 'file_date_early' as CodeErrorFile,
    FileDateTooEarly: 'file_date_too_early' as CodeErrorFile,
    FutureFileDate: 'future_file_date' as CodeErrorFile,
    TotalsNotMatchTheReport: 'totals_not_match_the_report' as CodeErrorFile,
    Empty: 'empty' as CodeErrorFile,
    AcceptingValidFile: 'accepting_valid_file' as CodeErrorFile,
    AmountFeedbackRecordsNotAppropriateFileAnswered: 'amount_feedback_records_not_appropriate_file_answered' as CodeErrorFile,
    ZipFileNotOpenedUnreadable: 'zip_file_not_opened/unreadable' as CodeErrorFile
};

