/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DepositStatus = 'share_holder' | 'self_employeed' | 'wage_worker';

export const DepositStatus = {
    ShareHolder: 'share_holder' as DepositStatus,
    SelfEmployeed: 'self_employeed' as DepositStatus,
    WageWorker: 'wage_worker' as DepositStatus
};

