/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DepositType = 'regular' | 'singular' | 'convalescence' | 'differences' | 'overtime' | 'convalescence_until' | 'convalescence_above';

export const DepositType = {
    Regular: 'regular' as DepositType,
    Singular: 'singular' as DepositType,
    Convalescence: 'convalescence' as DepositType,
    Differences: 'differences' as DepositType,
    Overtime: 'overtime' as DepositType,
    ConvalescenceUntil: 'convalescence_until' as DepositType,
    ConvalescenceAbove: 'convalescence_above' as DepositType
};

