/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DocumentTypes = 'other' | 'employer_deposition' | 'employer_poa' | 'authorization_protocol' | 'operation_protocol' | 'contract' | 'customer_details' | 'protocol_poa' | 'employer_signature';

export const DocumentTypes = {
    Other: 'other' as DocumentTypes,
    EmployerDeposition: 'employer_deposition' as DocumentTypes,
    EmployerPoa: 'employer_poa' as DocumentTypes,
    AuthorizationProtocol: 'authorization_protocol' as DocumentTypes,
    OperationProtocol: 'operation_protocol' as DocumentTypes,
    Contract: 'contract' as DocumentTypes,
    CustomerDetails: 'customer_details' as DocumentTypes,
    ProtocolPoa: 'protocol_poa' as DocumentTypes,
    EmployerSignature: 'employer_signature' as DocumentTypes
};

