/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type EmployeeStatus = 'daily' | 'lacks_payment' | 'seasonal' | 'contract_ended' | 'unpaid_loa' | 'death' | 'provident_fund_changed' | 'department_changed' | 'retired' | 'other' | 'new_employee' | 'contract_ended_compensation' | 'payment_report_future_work_departure' | 'monthly';

export const EmployeeStatus = {
    Daily: 'daily' as EmployeeStatus,
    LacksPayment: 'lacks_payment' as EmployeeStatus,
    Seasonal: 'seasonal' as EmployeeStatus,
    ContractEnded: 'contract_ended' as EmployeeStatus,
    UnpaidLoa: 'unpaid_loa' as EmployeeStatus,
    Death: 'death' as EmployeeStatus,
    ProvidentFundChanged: 'provident_fund_changed' as EmployeeStatus,
    DepartmentChanged: 'department_changed' as EmployeeStatus,
    Retired: 'retired' as EmployeeStatus,
    Other: 'other' as EmployeeStatus,
    NewEmployee: 'new_employee' as EmployeeStatus,
    ContractEndedCompensation: 'contract_ended_compensation' as EmployeeStatus,
    PaymentReportFutureWorkDeparture: 'payment_report_future_work_departure' as EmployeeStatus,
    Monthly: 'monthly' as EmployeeStatus
};

