/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type EventCode = '9303' | '9302' | '9301' | '9300';

export const EventCode = {
    _9303: '9303' as EventCode,
    _9302: '9302' as EventCode,
    _9301: '9301' as EventCode,
    _9300: '9300' as EventCode
};

