/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FeedbacksChangeStatusBodyCriteria } from './feedbacksChangeStatusBodyCriteria';
import { ManualStatus } from './manualStatus';


export interface FeedbacksChangeStatusBody { 
    content_type?: string;
    criteria?: FeedbacksChangeStatusBodyCriteria;
    ids?: Array<number>;
    status?: ManualStatus;
}
export namespace FeedbacksChangeStatusBody {
}


