/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApigeneralscommentCriteria } from './apigeneralscommentCriteria';


export interface GeneralsCommentBody { 
    content?: string;
    content_type?: string;
    criteria?: ApigeneralscommentCriteria;
    department_id?: string;
    employer_id?: number;
    event_code?: number;
    limit?: number;
    organization_id?: number;
    page?: number;
    ids?: Array<string>;
}

