/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InlineResponse20028Items { 
    id?: string;
    name?: string;
    code?: string;
    type?: string;
    number_a_max?: string;
    is_active?: boolean;
    company_name?: string;
    company_code?: string;
    full_name?: string;
    bank_name?: string;
    bank_number?: string;
    account?: string;
}

