/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse2005ReportsCompensation } from './inlineResponse2005ReportsCompensation';


export interface InlineResponse2005 { 
    message?: string;
    reportsCompensation?: Array<InlineResponse2005ReportsCompensation>;
    code?: number;
}

