/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatusProcess } from './statusProcess';


export interface InlineResponse20022 { 
    reason_refund?: boolean;
    group_things_ids?: Array<number>;
    num_file?: number;
    sum?: number;
    sent?: boolean;
    error_details?: string;
    is_null_company?: boolean;
    status?: StatusProcess;
    code?: number;
}
export namespace InlineResponse20022 {
}


