/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse20030Data } from './inlineResponse20030Data';


export interface InlineResponse20030 { 
    ok?: boolean;
    data?: Array<InlineResponse20030Data>;
}

