/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse20039Items } from './inlineResponse20039Items';
import { InlineResponse20039Other } from './inlineResponse20039Other';


export interface InlineResponse20039 { 
    items?: Array<InlineResponse20039Items>;
    total?: number;
    lastPage?: number;
    other?: InlineResponse20039Other;
    code?: number;
}

