/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse20034Employees } from './inlineResponse20034Employees';


export interface InlineResponse20034 { 
    employees?: Array<InlineResponse20034Employees>;
    products?: Array<InlineResponse20034Employees>;
    employer_products?: Array<InlineResponse20034Employees>;
}

