/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse20037Chat } from './inlineResponse20037Chat';
import { InlineResponse20037Messages } from './inlineResponse20037Messages';


export interface InlineResponse20037 { 
    messages?: Array<InlineResponse20037Messages>;
    chat?: InlineResponse20037Chat;
    messages_count?: number;
    code?: number;
}

