/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PermissionType } from './permissionType';


export interface InlineResponse2002Module { 
    id?: string;
    user_id?: string;
    name?: string;
    permission_type?: PermissionType;
}
export namespace InlineResponse2002Module {
}


