/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse20036Chat } from './inlineResponse20036Chat';
import { InlineResponse20036Messages } from './inlineResponse20036Messages';


export interface InlineResponse20036 { 
    messages?: Array<InlineResponse20036Messages>;
    chat?: InlineResponse20036Chat;
    messages_count?: number;
    code?: number;
}

