/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentTypes } from './documentTypes';


export interface InlineResponse20030Items { 
    id?: string;
    name?: string;
    ext?: string;
    description?: string;
    created_at?: string;
    employer_name?: number;
    employer_id?: string;
    document_type?: DocumentTypes;
}
export namespace InlineResponse20030Items {
}


