/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse20051Items } from './inlineResponse20051Items';


export interface InlineResponse20051 { 
    items?: Array<InlineResponse20051Items>;
    total?: number;
    lastPage?: number;
    code?: number;
}

