/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InlineResponse20048Items { 
    id?: number;
    employer_name?: string;
    employee_name?: string;
    identifier?: string;
    product_name?: string;
    product_code?: number;
}

