/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse20028Data } from './inlineResponse20028Data';


export interface InlineResponse20028 { 
    ok?: boolean;
    data?: Array<InlineResponse20028Data>;
}

