/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {
  ApiorganizationsgetOrganizationsDepartment,
} from './apiorganizationsgetOrganizationsDepartment';


export interface InlineResponse20045 { 
    employees?: Array<ApiorganizationsgetOrganizationsDepartment>;
    products?: Array<ApiorganizationsgetOrganizationsDepartment>;
    employer_products?: Array<ApiorganizationsgetOrganizationsDepartment>;
    code?: number;
}

