/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClauseType } from './clauseType';


export interface InlineResponse20039TransferClause { 
    clause_type?: ClauseType;
    transfer_sum?: number;
    transfer_percent?: number;
    exempt_sum?: number;
    id?: number;
}
export namespace InlineResponse20039TransferClause {
}


