/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {
  ApiorganizationsgetOrganizationsEmployer,
} from './apiorganizationsgetOrganizationsEmployer';


export interface InlineResponse20052 { 
    id?: string;
    name?: string;
    organization_group_id?: string;
    employer?: Array<ApiorganizationsgetOrganizationsEmployer>;
}

