/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse20039Employees } from './inlineResponse20039Employees';


export interface InlineResponse20039 { 
    employees?: Array<InlineResponse20039Employees>;
    products?: Array<InlineResponse20039Employees>;
    employer_products?: Array<InlineResponse20039Employees>;
    code?: number;
}

