/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse2006Items } from './inlineResponse2006Items';


export interface InlineResponse2006 { 
    items?: Array<InlineResponse2006Items>;
    lastPage?: number;
    total?: number;
}

