/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse20044Employees } from './inlineResponse20044Employees';


export interface InlineResponse20044 { 
    employees?: Array<InlineResponse20044Employees>;
    products?: Array<InlineResponse20044Employees>;
    employer_products?: Array<InlineResponse20044Employees>;
    code?: number;
}

