/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InlineResponse20042 { 
    id?: number;
    employee_chr_id?: number;
    original_employer_product_id?: number;
    original_group_name?: string;
    original_group_id?: number;
    current_group_id?: number;
    current_group_name?: string;
    employee_name?: string;
    identifier?: string;
    product_code?: number;
    product_name?: string;
    employer_product_code?: number;
    employer_product_name?: string;
    current_product_name?: string;
    current_product_code?: number;
    current_employer_product_name?: string;
    current_employer_product_code?: number;
}

