/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse20028Messages } from './inlineResponse20028Messages';
import { InlineResponse20028Chat } from './inlineResponse20028Chat';


export interface InlineResponse20028 { 
    messages?: Array<InlineResponse20028Messages>;
    chat?: InlineResponse20028Chat;
    messages_count?: number;
}

