/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatusProcess } from './statusProcess';


export interface InlineResponse2004ReportsDataProcesses { 
    id?: number;
    name?: string;
    created_at?: string;
    status_process?: StatusProcess;
    department_id?: number;
    employer_id?: number;
    total?: number;
    date?: string;
    employer_name?: string;
}
export namespace InlineResponse2004ReportsDataProcesses {
}


