/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse20033Chat } from './inlineResponse20033Chat';
import { InlineResponse20033Messages } from './inlineResponse20033Messages';


export interface InlineResponse20033 { 
    messages?: Array<InlineResponse20033Messages>;
    chat?: InlineResponse20033Chat;
    messages_count?: number;
    code?: number;
}

