/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse20029Items } from './inlineResponse20029Items';
import { InlineResponse20029Other } from './inlineResponse20029Other';


export interface InlineResponse20029 { 
    items?: Array<InlineResponse20029Items>;
    total?: number;
    lastPage?: number;
    other?: InlineResponse20029Other;
}

