/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReportingType } from './reportingType';
import { CodeErrorFile } from './codeErrorFile';
import { StatusCompensation } from './statusCompensation';
import { FeedbackLevel } from './feedbackLevel';
import { InlineResponse2007Comments } from './inlineResponse2007Comments';
import { ProductType } from './productType';
import { CodeError } from './codeError';
import { SendingMethod } from './sendingMethod';


export interface InlineResponse2007 { 
    id?: number;
    created_at?: string;
    updated_at?: string;
    user_id?: number;
    employer_name?: string;
    employer_id?: number;
    department_name?: string;
    department_id?: number;
    employee_name?: string;
    is_file?: boolean;
    identifier?: string;
    company_name?: string;
    company_id?: number;
    alidity_date?: string;
    sending_method?: SendingMethod;
    product_type?: ProductType;
    projected_balance?: number;
    reported_balance?: number;
    portal_balance?: number;
    status?: StatusCompensation;
    contents?: string;
    closed_at?: string;
    files?: Array<string>;
    code_error?: CodeError;
    error_details?: string;
    code_error_file?: CodeErrorFile;
    error_details_file?: string;
    error_sent_failed?: string;
    feedback_level?: FeedbackLevel;
    answering_manufacturer?: string;
    username?: string;
    reporting_type?: ReportingType;
    has_by_safebox?: boolean;
    has_file_feedback?: boolean;
    xml_name?: string;
    extend_clearing?: string;
    inquiries?: Array<string>;
    comments?: Array<InlineResponse2007Comments>;
    name?: string;
    num_clearing?: number;
    product_code?: string;
}
export namespace InlineResponse2007 {
}


