/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse20030Employees } from './inlineResponse20030Employees';


export interface InlineResponse20030 { 
    employees?: Array<InlineResponse20030Employees>;
    products?: Array<InlineResponse20030Employees>;
    employer_products?: Array<InlineResponse20030Employees>;
}

