/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse2004ReportsDataProcesses } from './inlineResponse2004ReportsDataProcesses';


export interface InlineResponse2004ReportsData { 
    processes?: Array<InlineResponse2004ReportsDataProcesses>;
    compensation_open?: number;
    compensation_close?: number;
    files?: number;
    files_loading?: number;
    files_transmitted?: number;
    employees_zero_count?: number;
    employees_no_zero_count?: number;
    file_feedback_a_failed?: number;
    file_not_defrayed?: number;
    file_partially_paid?: number;
    file_fully_defrayed?: number;
    mtb_defrayed?: number;
    mtb_not_defrayed?: number;
}

