/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApigeneralsbanksBankBranches } from './apigeneralsbanksBankBranches';


export interface InlineResponse20043 { 
    id?: string;
    name?: string;
    bank_branches?: Array<ApigeneralsbanksBankBranches>;
}

