/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClauseType } from './clauseType';


export interface InlineResponse20043 { 
    clause_type?: ClauseType;
    transfer_sum?: number;
    transfer_percent?: number;
    exempt_sum?: number;
    id?: number;
    predicted_sum?: number;
    predicted_percent?: number;
    guid?: string;
    previous_guid?: string;
    status?: string;
    error_type?: string;
    error_details?: string;
    expected_percent?: number;
    expected_sum?: number;
    exempt?: number;
    percent?: number;
    sum?: number;
    salary_calculated?: number;
    current_provision_rate_aca?: number;
    expected_update_date_aca_tariff?: string;
    future_provision_rate_aca?: number;
    licensee_name?: string;
    licensed_identifier?: string;
    email_address_licensee?: string;
}
export namespace InlineResponse20043 {
}


