/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse20031Messages } from './inlineResponse20031Messages';
import { InlineResponse20031Chat } from './inlineResponse20031Chat';


export interface InlineResponse20031 { 
    messages?: Array<InlineResponse20031Messages>;
    chat?: InlineResponse20031Chat;
    messages_count?: number;
}

