/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse20017Items } from './inlineResponse20017Items';


export interface InlineResponse20017 { 
    items?: Array<InlineResponse20017Items>;
    total?: number;
    lastPage?: number;
}

