/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatusChat } from './statusChat';


export interface InlineResponse2008 { 
    id?: number;
    created_at?: string;
    updated_at?: string;
    content?: string;
    subject?: string;
    subject_id?: number;
    tat_subject?: string;
    tat_subject_id?: string;
    status?: StatusChat;
    creator_name?: string;
    employer_name?: string;
    employer_id?: number;
    employee_name?: string;
    new_messages?: number;
    operator_name?: string;
}
export namespace InlineResponse2008 {
}


