/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse20033Other } from './inlineResponse20033Other';
import { InlineResponse20033Items } from './inlineResponse20033Items';


export interface InlineResponse20033 { 
    items?: Array<InlineResponse20033Items>;
    total?: number;
    lastPage?: number;
    other?: InlineResponse20033Other;
}

