/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiproductsfullCompanyProduct } from './apiproductsfullCompanyProduct';


export interface InlineResponse20030 { 
    id?: string;
    name?: string;
    code?: string;
    product?: Array<ApiproductsfullCompanyProduct>;
}

