/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductType } from './productType';


export interface InlineResponse2005ReportsCompensation { 
    created_at?: string;
    employee_first_name?: string;
    employee_identifier?: string;
    employee_last_name?: string;
    product_type?: ProductType;
}
export namespace InlineResponse2005ReportsCompensation {
}


