/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiproductsfullCompanyBankAccount } from './apiproductsfullCompanyBankAccount';
import { Comment } from './comment';
import { FileType } from './fileType';
import { InlineResponse20018EmployerProducts } from './inlineResponse20018EmployerProducts';
import { PaymentType } from './paymentType';
import { ProductType } from './productType';
import { StatusFileFeedback } from './statusFileFeedback';
import { StatusGroupThing } from './statusGroupThing';


export interface InlineResponse20018Items { 
    file_type?: FileType;
    file_id?: number;
    company_name?: string;
    employer_products?: Array<InlineResponse20018EmployerProducts>;
    product_type?: ProductType;
    product_code?: string;
    paid_account_number?: string;
    is_primary?: boolean;
    payment_identifier?: string;
    payment_additional_info?: ApiproductsfullCompanyBankAccount;
    payment_date?: string;
    payment_type?: PaymentType;
    file_total?: string;
    group_id?: number;
    status_sent?: StatusFileFeedback;
    status?: StatusGroupThing;
    ref_path?: string;
    comment?: string;
    comments?: Array<Comment>;
    is_relevant?: boolean;
    in_process?: boolean;
    request_open?: string;
}
export namespace InlineResponse20018Items {
}


