/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ManualStatus = 'fully_defrayed_manual' | 'fully_defrayed_no_errors' | 'returned_to_employer' | 'no_relevant' | 'in_treatment_operator' | 'in_treatment_employer' | 'in_treatment_myhr' | 'in_treatment_manufacturer';

export const ManualStatus = {
    FullyDefrayedManual: 'fully_defrayed_manual' as ManualStatus,
    FullyDefrayedNoErrors: 'fully_defrayed_no_errors' as ManualStatus,
    ReturnedToEmployer: 'returned_to_employer' as ManualStatus,
    NoRelevant: 'no_relevant' as ManualStatus,
    InTreatmentOperator: 'in_treatment_operator' as ManualStatus,
    InTreatmentEmployer: 'in_treatment_employer' as ManualStatus,
    InTreatmentMyhr: 'in_treatment_myhr' as ManualStatus,
    InTreatmentManufacturer: 'in_treatment_manufacturer' as ManualStatus
};

