/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Apigenerals1newInquiryInquiry } from './apigenerals1newInquiryInquiry';


export interface Model1NewInquiryBody { 
    inquiry?: Apigenerals1newInquiryInquiry;
    employer_id?: number;
    opswatIds?: Array<string>;
}

