/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Apigenerals1inquiriesInquiry } from './apigenerals1inquiriesInquiry';


export interface Model1InquiriesBody { 
    inquiry?: Apigenerals1inquiriesInquiry;
    employer_id?: number;
    opswatIds?: Array<string>;
}

