/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiprocessesunlockProcessFilesCriteria } from './apiprocessesunlockProcessFilesCriteria';
import { ReasonRefund } from './reasonRefund';


export interface MtbCreateOrUpdateMtbGroupBody { 
    ids?: Array<number>;
    type?: ReasonRefund;
    criteria?: ApiprocessesunlockProcessFilesCriteria;
    bank_account_id?: number;
    product_id?: number;
    group_name?: string;
    confirmation?: number;
}
export namespace MtbCreateOrUpdateMtbGroupBody {
}


