/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type PaymentType = 'masav' | 'direct_debit' | 'check' | 'bank_transfer' | 'direct_debit_authorization';

export const PaymentType = {
    Masav: 'masav' as PaymentType,
    DirectDebit: 'direct_debit' as PaymentType,
    Check: 'check' as PaymentType,
    BankTransfer: 'bank_transfer' as PaymentType,
    DirectDebitAuthorization: 'direct_debit_authorization' as PaymentType
};

