/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type PermissionType = 'read' | 'write' | 'all' | 'employer';

export const PermissionType = {
    Read: 'read' as PermissionType,
    Write: 'write' as PermissionType,
    All: 'all' as PermissionType,
    Employer: 'employer' as PermissionType
};

