/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type PriorityType = 'standard' | 'conservation' | 'strategic' | 'on_process';

export const PriorityType = {
    Standard: 'standard' as PriorityType,
    Conservation: 'conservation' as PriorityType,
    Strategic: 'strategic' as PriorityType,
    OnProcess: 'on_process' as PriorityType
};

