/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CriteriaProcess } from './criteriaProcess';
import { UpdateFileType } from './updateFileType';


export interface ProcessesUpdateBody { 
    file_id?: Array<number>;
    params?: boolean;
    type?: UpdateFileType;
    criteria?: CriteriaProcess;
    processId?: number;
}
export namespace ProcessesUpdateBody {
}


