/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiprocessesunlockProcessFilesCriteria } from './apiprocessesunlockProcessFilesCriteria';
import { ReasonRefund } from './reasonRefund';


export interface ProcessesUpdateReasonRefundBody { 
    filesList?: Array<number>;
    reason?: ReasonRefund;
    criteria?: ApiprocessesunlockProcessFilesCriteria;
}
export namespace ProcessesUpdateReasonRefundBody {
}


