/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ProcessType = 'employer_payment' | 'employer_withdrawal' | 'regular_fix' | 'positive_negative_fix' | 'positive_2_negative_fix' | 'positive_3_negative_fix' | 'direct_employer' | 'manual_payment' | 'unknown';

export const ProcessType = {
    EmployerPayment: 'employer_payment' as ProcessType,
    EmployerWithdrawal: 'employer_withdrawal' as ProcessType,
    RegularFix: 'regular_fix' as ProcessType,
    PositiveNegativeFix: 'positive_negative_fix' as ProcessType,
    Positive2NegativeFix: 'positive_2_negative_fix' as ProcessType,
    Positive3NegativeFix: 'positive_3_negative_fix' as ProcessType,
    DirectEmployer: 'direct_employer' as ProcessType,
    ManualPayment: 'manual_payment' as ProcessType,
    Unknown: 'unknown' as ProcessType
};

