/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ProductType = 'provident' | 'executive' | 'pension' | 'study';

export const ProductType = {
    Provident: 'provident' as ProductType,
    Executive: 'executive' as ProductType,
    Pension: 'pension' as ProductType,
    Study: 'study' as ProductType
};

