/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ReasonRefund = 'wrong_product_type' | 'wrong_employee_deposit' | 'deposit_month_incorrect' | 'correction_error_calculation_wages' | 'deposit_wrong_management_company' | 'employee_moved_another_provident_fund' | 'collective_agreement' | 'overdose_per_component' | 'acha_premium_excess' | 'overpayment_per_employee_after';

export const ReasonRefund = {
    WrongProductType: 'wrong_product_type' as ReasonRefund,
    WrongEmployeeDeposit: 'wrong_employee_deposit' as ReasonRefund,
    DepositMonthIncorrect: 'deposit_month_incorrect' as ReasonRefund,
    CorrectionErrorCalculationWages: 'correction_error_calculation_wages' as ReasonRefund,
    DepositWrongManagementCompany: 'deposit_wrong_management_company' as ReasonRefund,
    EmployeeMovedAnotherProvidentFund: 'employee_moved_another_provident_fund' as ReasonRefund,
    CollectiveAgreement: 'collective_agreement' as ReasonRefund,
    OverdosePerComponent: 'overdose_per_component' as ReasonRefund,
    AchaPremiumExcess: 'acha_premium_excess' as ReasonRefund,
    OverpaymentPerEmployeeAfter: 'overpayment_per_employee_after' as ReasonRefund
};

