/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ReportingType = 'file_level_deferment' | 'lists_incorrect_entries' | 'confirm_full_integrity_file';

export const ReportingType = {
    FileLevelDeferment: 'file_level_deferment' as ReportingType,
    ListsIncorrectEntries: 'lists_incorrect_entries' as ReportingType,
    ConfirmFullIntegrityFile: 'confirm_full_integrity_file' as ReportingType
};

