/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Roles = 'role_super_user' | 'role_admin' | 'role_operator' | 'role_employer' | 'role_service' | 'service_manager';

export const Roles = {
    RoleSuperUser: 'role_super_user' as Roles,
    RoleAdmin: 'role_admin' as Roles,
    RoleOperator: 'role_operator' as Roles,
    RoleEmployer: 'role_employer' as Roles,
    RoleService: 'role_service' as Roles,
    ServiceManager: 'service_manager' as Roles
};

