/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SendingMethod = 'safebox' | 'email' | 'clearing' | 'portal';

export const SendingMethod = {
    Safebox: 'safebox' as SendingMethod,
    Email: 'email' as SendingMethod,
    Clearing: 'clearing' as SendingMethod,
    Portal: 'portal' as SendingMethod
};

