/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Src = 'friend' | 'contact_us' | 'pension_settlement' | 'personal_portfolio_manager' | 'form_161' | 'private_area';

export const Src = {
    Friend: 'friend' as Src,
    ContactUs: 'contact_us' as Src,
    PensionSettlement: 'pension_settlement' as Src,
    PersonalPortfolioManager: 'personal_portfolio_manager' as Src,
    Form161: 'form_161' as Src,
    PrivateArea: 'private_area' as Src
};

