/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type StatusFeedback = 'fix' | 'error_name' | 'new' | 'not_found' | 'partial' | 'irrelevant';

export const StatusFeedback = {
    Fix: 'fix' as StatusFeedback,
    ErrorName: 'error_name' as StatusFeedback,
    New: 'new' as StatusFeedback,
    NotFound: 'not_found' as StatusFeedback,
    Partial: 'partial' as StatusFeedback,
    Irrelevant: 'irrelevant' as StatusFeedback
};

