/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type StatusChat = 'close' | 'in_treatment' | 'open';

export const StatusChat = {
    Close: 'close' as StatusChat,
    InTreatment: 'in_treatment' as StatusChat,
    Open: 'open' as StatusChat
};

