/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type StatusGroupThing = 'not_sent' | 'sent' | 'locked';

export const StatusGroupThing = {
    NotSent: 'not_sent' as StatusGroupThing,
    Sent: 'sent' as StatusGroupThing,
    Locked: 'locked' as StatusGroupThing
};

