/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type StatusCompensation = 'feedback_a' | 'feedback_b' | 'open' | 'sent' | 'sent_failed' | 'closed_manually' | 'closed';

export const StatusCompensation = {
    FeedbackA: 'feedback_a' as StatusCompensation,
    FeedbackB: 'feedback_b' as StatusCompensation,
    Open: 'open' as StatusCompensation,
    Sent: 'sent' as StatusCompensation,
    SentFailed: 'sent_failed' as StatusCompensation,
    ClosedManually: 'closed_manually' as StatusCompensation,
    Closed: 'closed' as StatusCompensation
};

