/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type StatusEmployer = 'moved_association' | 'active' | 'inactive' | 'on_process';

export const StatusEmployer = {
    MovedAssociation: 'moved_association' as StatusEmployer,
    Active: 'active' as StatusEmployer,
    Inactive: 'inactive' as StatusEmployer,
    OnProcess: 'on_process' as StatusEmployer
};

