/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SubjectChat = 'bookkeeping' | 'feedback' | 'message_from_company' | 'documents' | 'deposits' | 'references' | 'employer_reports' | 'employee_reports' | 'refund' | 'general';

export const SubjectChat = {
    Bookkeeping: 'bookkeeping' as SubjectChat,
    Feedback: 'feedback' as SubjectChat,
    MessageFromCompany: 'message_from_company' as SubjectChat,
    Documents: 'documents' as SubjectChat,
    Deposits: 'deposits' as SubjectChat,
    References: 'references' as SubjectChat,
    EmployerReports: 'employer_reports' as SubjectChat,
    EmployeeReports: 'employee_reports' as SubjectChat,
    Refund: 'refund' as SubjectChat,
    General: 'general' as SubjectChat
};

