/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TransmissionProductAuto = 'link' | 'remainder' | 'no_remainder';

export const TransmissionProductAuto = {
    Link: 'link' as TransmissionProductAuto,
    Remainder: 'remainder' as TransmissionProductAuto,
    NoRemainder: 'no_remainder' as TransmissionProductAuto
};

