/**
 * Smarti
 * Smarti1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dinav@smarti-saas.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TypeLoad = 'manual' | 'file';

export const TypeLoad = {
    Manual: 'manual' as TypeLoad,
    File: 'file' as TypeLoad
};

